# fly.toml app configuration file generated for caleb-stromberg-blog-server on 2023-07-19T12:27:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caleb-stromberg-blog-server"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
